GET http://localhost:4000/accounts/teachers
###
GET http://localhost:4000/admin/settings/Strands
###
POST http://localhost:4000/admin/settings/addStrand
Content-Type: application/json

{
   "year":"Grade12","strand" : "ABM","section":"A"
}
###
POST http://localhost:4000/accounts/loginTwo
Content-Type: application/json

{
   "username":"student11","password" : "sdqdqsd"
}
###
GET http://localhost:4000/admin/students
###
GET http://localhost:4000/teacher/getAllPresences
###
PUT http://localhost:4000/admin/updateStudentStatus/1
Content-Type: application/json

{
   "status":"active"
}
###
POST http://localhost:4000/chefDep/insertSeance
Content-Type: application/json

{
   "day":"Username","start_time" : "gdfgfd","end_time":"","id_groupe":1,"id_module":1,"id_teacher":1
}
###
POST http://localhost:4000/accounts/addPresenceAndroid
Content-Type: application/json

{
   "id_student":3,"id_seance":6,"presence":"present","retard":0
}
###
GET http://localhost:4000/chefDep/getAllJustifications
