GET http://localhost:4000/accounts/teachers
###
GET http://localhost:4000/admin/settings/Strands
###
POST http://localhost:4000/admin/settings/addStrand
Content-Type: application/json

{
   "year":"Grade12","strand" : "ABM","section":"A"
}
###
POST http://localhost:4000/accounts/loginTwo
Content-Type: application/json

{
   "username":"student2","password" : "student2"
}
###
GET http://localhost:4000/admin/students
###
GET http://localhost:4000/teacher/getAllPresences
###
PUT http://localhost:4000/admin/updateStudentStatus/1
Content-Type: application/json

{
   "status":"active"
}
###
POST http://localhost:4000/teacher/insertAnnonce/90
Content-Type: application/json

{
   "id_groupe":3,"contenu_annonce" : "gdfgfd"
}
###
POST http://localhost:4000/accounts/addPresenceAndroid
Content-Type: application/json

{
   "id_student":3,"id_seance":6,"presence":"present","retard":0
}
###
GET http://localhost:4000/chefDep/getAllJustifications
###
GET http://localhost:4000/accounts/studentAbsence/4
###
GET http://localhost:4000/teacher/getAnnonceByTeacher/89
###
GET http://localhost:4000/teacher/getAnnonceByGroupe/4